### DISCUSSION TITLE
Empty Simulation Box in generated conf.lmp

### DISCUSSION THREAD

**Discussion by ghost** [deepmodeling/dpgen#1410] [Q&A] [answered]
A box is not defined in the automatically generated conf.lmp file, resulting in an execution error.

```

7 atoms
1 atom types
   0.0000000000    0.0000000000 xlo xhi
   0.0000000000    0.0000000000 ylo yhi
   0.0000000000    0.0000000000 zlo zhi
   0.0000000000    0.0000000000    0.0000000000 xy xz yz

Atoms # atomic

     1      1    9.5278130000    0.0000000000    1.9284020000
     2      1   11.2698910000    2.1932670000    0.8577270000
     3      1    9.2812530000    4.3974890000    0.4143490000
     4      1    7.0532840000    4.5082370000    2.4227710000
     5      1    4.7742510000    2.7310510000    1.6316740000
     6      1    2.4025010000    1.8857890000    0.0000000000
     7      1    0.0000000000    2.4361270000    1.7127590000
```

param.yaml

```
type_map:
  - Na
init_data_prefix: ''
init_data_sys:
  - /home/sekinelabo/Documents/DeepMD-Sodium/dpgen/data/Na7/
sys_format: deepmd/npy
sys_configs:
  - - /home/sekinelabo/Documents/DeepMD-Sodium/dpgen/data/Na7/
numb_models: 4
default_training_param:
  model:
    type_map:
    - Na
    data_stat_nbatch: 1
    type: standard
    descriptor:
      type: se_e2_a
      sel:
      - 60
      rcut: 6.0
      rcut_smth: 1.8
      neuron:
      - 25
      - 50
      - 100
      axis_neuron: 8
      resnet_dt: false
      precision: float64
      seed: 1
    fitting_net:
      type: ener
      neuron:
      - 120
      - 120
      - 120
      precision: float64
      resnet_dt: true
      seed: 1
  learning_rate:
    type: exp
    start_lr: 0.001
    stop_lr: 3.0e-08
    decay_steps: 5000
  loss:
    type: ener
    start_pref_e: 0.02
    limit_pref_e: 1
    start_pref_f: 1000
    limit_pref_f: 1
    start_pref_v: 0
    limit_pref_v: 0
  training:
    numb_steps: 1000000
    seed: 1
    disp_file: lcurve.out
    disp_freq: 100
    save_freq: 1000
    save_ckpt: model.ckpt
    disp_training: true
    time_training: true
    profiling: false
    profiling_file: timeline.json
fp_task_max: 20
fp_task_min: 1
model_devi_engine: lammps
model_devi_jobs:
  - sys_idx:
      - 0
    temps:
      - 300
    press:
      - 1
    nsteps: 1000
    ensemble: nvt
    trj_freq: 10
    _idx: "00"
  - sys_idx:
      - 0
    temps:
      - 300
    press:
      - 1
    nsteps: 3000
    ensemble: nvt
    trj_freq: 10
    _idx: "01"
model_devi_dt: 0.002
model_devi_skip: 0
model_devi_f_trust_lo: 0.05
model_devi_f_trust_hi: 0.15
fp_style: gaussian
use_clusters: false
fp_params:
  keywords: P B3LYP/6-311+g(d) force
  nproc: 14
  charge: 0
```

```
~/Documents/DeepMD-Sodium/dpgen/data/Na7 $ tree
.
├── nopbc
├── set.000
│   ├── box.npy
│   ├── coord.npy
│   ├── energy.npy
│   └── force.npy
├── type.raw
└── type_map.raw

1 directory, 7 files

```
box is defined in box.npy:
1.000000000000000000e+02 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 1.000000000000000000e+02 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 1.000000000000000000e+02(first line)

Should I make lammpf conf.lmp file from deepmd data for DP-GEN iteration?
