### ISSUE TITLE
[feature suggest] allow comments in json

### ISSUE THREAD

**Issue by thangckt** [deepmodeling/dpgen#1626]
### Summary

Dear Developers,

I made some change that allows comments in json setting file, something like this
```jsonc

    // Model deviation
    "model_devi_dt": 0.002,
    "model_devi_skip": 0,
    "model_devi_f_trust_lo": 0.05,                 // this is comment
    "model_devi_f_trust_hi": 0.15,
    "model_devi_e_trust_lo": 10000000000.0,  
    "model_devi_e_trust_hi": 10000000000.0,
    "model_devi_clean_traj": true,              // this is comment
    "model_devi_jobs": [
        { "sys_idx": [ 0 ], "temps": [ 100 ], "press": [ 1.0 ], "trj_freq": 10, "nsteps": 300, "ensemble": "nvt", "_idx": "00" }
        // { "sys_idx": [ 1 ], "temps": [ 300 ], "press": [ 1.0 ], "trj_freq": 10, "nsteps": 3000, "ensemble": "nvt", "_idx": "01" }
    ],

    // DFT
    "fp_style": "vasp",
    "fp_task_max": 20,
    "fp_task_min": 1
}
```
This is helpful in some situations. 
If you are interested in, I can make PR.

### DP-GEN Version

.

### Platform, Python Version, etc

.

### Details

.

**Comment by njzjz** [comment]
You can rename your file to `xx.yaml`. YAML is a superset of JSON and supports comments.

```yaml
    # Model deviation
    "model_devi_dt": 0.002,
    "model_devi_skip": 0,
    "model_devi_f_trust_lo": 0.05,                 # this is comment
    "model_devi_f_trust_hi": 0.15,
    "model_devi_e_trust_lo": 10000000000.0,  
    "model_devi_e_trust_hi": 10000000000.0,
    "model_devi_clean_traj": true,              # this is comment
    "model_devi_jobs": [
        { "sys_idx": [ 0 ], "temps": [ 100 ], "press": [ 1.0 ], "trj_freq": 10, "nsteps": 300, "ensemble": "nvt", "_idx": "00" }
        # { "sys_idx": [ 1 ], "temps": [ 300 ], "press": [ 1.0 ], "trj_freq": 10, "nsteps": 3000, "ensemble": "nvt", "_idx": "01" }
    ],

    # DFT
    "fp_style": "vasp",
    "fp_task_max": 20,
    "fp_task_min": 1
}
```
